### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by kajikaferus** [defeatedcrow/HeatAndClimateLib#25]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2020-06-10 22:01:18 EDT
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from HeatAndClimateLib (dcs_lib)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
    at com.google.gson.Gson.fromJson(Gson.java:899)
    at defeatedcrow.hac.core.fluid.FluidIDRegisterDC.pre(FluidIDRegisterDC.java:140)
    at defeatedcrow.hac.config.ClimateConfig.load(ClimateConfig.java:33)
    at defeatedcrow.hac.core.ClimateCore.preInit(ClimateCore.java:69)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
    at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
    at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)
    at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
    at com.google.gson.Gson.fromJson(Gson.java:887)
    ... 43 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1360676544 bytes (1297 MB) / 2003304448 bytes (1910 MB) up to 10021765120 bytes (9557 MB)
  JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10752m -Xms256m -XX:PermSize=256m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 50 mods loaded, 50 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                              | Version                  | Source                                      | Signature                                |
       |:----- |:------------------------------- |:------------------------ |:------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft                       | 1.12.2                   | minecraft.jar                               | None                                     |
       | LCH   | mcp                             | 9.42                     | minecraft.jar                               | None                                     |
       | LCH   | FML                             | 8.0.99.99                | forge-1.12.2-14.23.5.2854.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | forge                           | 14.23.5.2854             | forge-1.12.2-14.23.5.2854.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | dcs_asm                         | 2.1.0                    | minecraft.jar                               | 4cd12b92959105443b7b694fffe0cea9ed004886 |
       | LCH   | jei                             | 4.15.0.291               | jei_1.12.2-4.15.0.291.jar                   | None                                     |
       | LCH   | mantle                          | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                    | None                                     |
       | LCH   | tconstruct                      | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar            | None                                     |
       | LCH   | betterwithmods                  | 1.12-2.3.23              | BetterWithMods-1.12-2.3.23.jar              | None                                     |
       | LCH   | appleskin                       | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                  | None                                     |
       | LCH   | conarm                          | 1.2.5.9                  | conarm-1.12.2-1.2.5.9.jar                   | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCH   | armoryexpansion                 | 1.4.2                    | armoryexpansion-1.4.2.jar                   | None                                     |
       | LCH   | armoryexpansion-custommaterials | 1.4.2                    | armoryexpansion-1.4.2.jar                   | None                                     |
       | LCH   | llibrary                        | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                  | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCH   | iceandfire                      | 1.9.1                    | iceandfire-1.9.1-1.12.2.jar                 | None                                     |
       | LCH   | armoryexpansion-iceandfire      | 1.4.2                    | armoryexpansion-1.4.2.jar                   | None                                     |
       | LCH   | armoryexpansion-matteroverdrive | 1.4.2                    | armoryexpansion-1.4.2.jar                   | None                                     |
       | LCH   | mmdlib                          | 1.0.0-rc2                | MMDLib-1.12-1.0.0-rc2.36.jar                | None                                     |
       | LCH   | basemetals                      | 2.5.0-rc2                | BaseMetals-1.12-2.5.0-rc2.332.jar           | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | betterwithlib                   | ${version}               | BetterWithLib-1.12-1.5.jar                  | None                                     |
       | LCH   | blockdrops                      | 1.4.0                    | blockdrops-1.12.2-1.4.0.jar                 | None                                     |
       | LCH   | bookworm                        | 1.12.2-2.5.1             | bookworm-1.12.2-2.5.1.jar                   | None                                     |
       | LCH   | reskillable                     | 1.12.2-1.13.0            | Reskillable-1.12.2-1.13.0.jar               | None                                     |
       | LCH   | compatskills                    | 1.12.2-1.17.0            | CompatSkills-1.12.2-1.17.0.jar              | None                                     |
       | LCH   | controlling                     | 3.0.9                    | Controlling-3.0.9.jar                       | None                                     |
       | LCH   | cxlibrary                       | 1.6.1                    | cxlibrary-1.12.1-1.6.1.jar                  | None                                     |
       | LCH   | familiarfauna                   | 1.0.11                   | FamiliarFauna-1.12.2-1.0.11.jar             | None                                     |
       | LCH   | gravestone                      | 1.10.3                   | gravestone-1.10.3.jar                       | None                                     |
       | LCE   | dcs_lib                         | 3.3.2                    | HeatAndClimateLib_1.12.2-3.3.2.jar          | 4cd12b92959105443b7b694fffe0cea9ed004886 |
       | LC    | dcs_climate                     | 3.3.6                    | HeatAndClimateMod_1.12.2-3.3.6.jar          | 4cd12b92959105443b7b694fffe0cea9ed004886 |
       | LC    | improvedbackpacks               | 1.12.2-1.5.0.0           | ImprovedBackpacks-1.12.2-1.5.0.0.jar        | None                                     |
       | LC    | jeiintegration                  | 1.6.0                    | jeiintegration_1.12.2-1.6.0.jar             | None                                     |
       | LC    | journeymap                      | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                 | None                                     |
       | LC    | libraryex                       | 1.1.3                    | LibraryEx-1.12.2-1.1.3.jar                  | None                                     |
       | LC    | lycanitesmobs                   | 2.0.7.2 - MC 1.12.2      | lycanitesmobs-1.12.2-2.0.7.2.jar            | None                                     |
       | LC    | modernmetals                    | 2.5.0-rc2                | ModernMetals-1.12-2.5.0-rc2.152.jar         | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LC    | morefurnaces                    | 1.10.5                   | MoreFurnaces-1.12.2-1.10.6.jar              | None                                     |
       | LC    | netherex                        | 2.1.7                    | NetherEx-1.12.2-2.1.7.jar                   | None                                     |
       | LC    | oreexcavation                   | 1.4.150                  | OreExcavation-1.4.150.jar                   | None                                     |
       | LC    | orespawn                        | 3.3.1                    | OreSpawn-1.12-3.3.1.179.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LC    | sereneseasons                   | 1.2.18                   | SereneSeasons-1.12.2-1.2.18-universal.jar   | None                                     |
       | LC    | spartanweaponry                 | beta 1.3.8               | SpartanWeaponry-1.12.2-beta-1.3.8.jar       | None                                     |
       | LC    | spartanfire                     | 0.08                     | spartanfire-0.08.jar                        | None                                     |
       | LC    | spartanshields                  | 1.5.4                    | SpartanShields-1.12.2-1.5.4.jar             | None                                     |
       | LC    | tinkersjei                      | 1.2                      | tinkersjei-1.2.jar                          | None                                     |
       | LC    | tinkertoolleveling              | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar         | None                                     |
       | LC    | vanillafix                      | 1.0.10-150               | VanillaFix-1.0.10-150.jar                   | None                                     |
       | LC    | zawa                            | 1.12.2-2.0.35            | zawa-1.12.2-2.0.35.jar                      | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |
       | LC    | phosphor-lighting               | 1.12.2-0.2.6             | phosphor-1.12.2-0.2.6+build50-universal.jar | f0387d288626cc2d937daa504e74af570c52a2f1 |
       | LC    | armoryexpansion-conarm          | 1.4.2                    | armoryexpansion-1.4.2.jar                   | None                                     |
  Loaded coremods (and transformers): llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      DCASMPlugin (HeatAndClimateLib_1.12.2-3.3.2.jar)
                                        defeatedcrow.hac.asm.DCMethodTransformer
                                      CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
                                        cubex2.cxlibrary.CoreModTransformer
                                      LoadingPlugin (Reskillable-1.12.2-1.13.0.jar)
                                        codersafterdark.reskillable.base.asm.ClassTransformer
                                      iceandfire (iceandfire-1.9.1-1.12.2.jar)
                                        com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
                                      LoadingPlugin (BetterWithLib-1.12-1.5.jar)
                                        betterwithmods.library.core.ClassTransformer
  GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.5058' Renderer: 'Intel(R) HD Graphics 4400'
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
  Suspected Mods: HeatAndClimateLib (dcs_lib)
  Launched Version: forge-14.23.5.2854
  LWJGL: 2.9.4
  OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 20.19.15.5058, Intel
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 4x Intel(R) Core(TM) i3-4130T CPU @ 2.90GHz

**Comment by defeatedcrow** [comment]
The cause has been indicated.
>Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
This is because the contents of fluids.json are incorrect.

fluids.json is not a file that should be edited by the player, and the editing function is not open to the user. If you edit it by mistake, deleting it will automatically regenerate it.

**Comment by kajikaferus** [comment]
Oh ok thanks
